const PALETTE = {
  BEIGE: "#ffd050",
  YELLOW: "#F4B926",
  MINT: "#53BCBD",
  KAKI: "#6D583C",
  GRAY: "#DBD6C4",
  BLACK: "#494949",
  DARKER: "#382D2E",
  PINK: "#F661BD"
};

const STATUS = {
  DEFAULT: PALETTE.BEIGE,
  READ: PALETTE.MINT,
  STAR: PALETTE.PINK,
};

export { PALETTE, STATUS };
