const PALETTE = {
  BEIGE: "#ffd050",
  YELLOW: "#F0C102",
  BLUE: "#08A6D3",
  KAKI: "#6D583C",
  GRAY: "#DBD6C4",
  BLACK: "#494949",
  DARKER: "#382D2E",
  PINK: "#F661BD"
};

const STATUS = {
  DEFAULT: PALETTE.BEIGE,
  READ: PALETTE.GRAY,
  STAR: PALETTE.BLUE,
  COLLECTION: PALETTE.PINK,
};

export { PALETTE, STATUS };
